[package]
name = "pg-extended-sqlx-queries-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
[lib]
proc-macro = true
[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.5"

[features]
