name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run cargo test --all-features
        run: cargo test --all-features
      - name: Run cargo test no features
        run: cargo test --no-default-features
      - name: Cargo Test with JSON
        run: cargo test --no-default-features --features json
      - name: Cargo Test with chrono
        run: cargo test --no-default-features --features json
      - name: Cargo Test with uuid
        run: cargo test --no-default-features --features json